version: 2

jobs:

  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: 
          name: Run NPM tests
          command: |
            npm install
            npm run test

  publish:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Publish to NPM
          command: |
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            npm publish

workflows:
  build-and-deploy:
    jobs:
      - test

      - publish:
          requires:
            - node/test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/