version: 2.1

orbs:
  node: circleci/node@3.0.1

jobs:
  publish:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "hello world"

workflows:
  build-and-publish:
    jobs:
      - node/test
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/ # Important
      - publish:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
