version: 2.1

orbs:
  node: circleci/node@3.0.1

jobs:
  publish:
    docker: 
      - image: circleci/node 
    steps:
      - checkout 
      - run: echo "hello deploy" 
    
workflows:
  test-and-publish:
    jobs:
      - node/test:
          filters:
            tags:
              only: /.*/

      - publish:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
