version: 2

jobs:
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "hello from test"

  deploy:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "hello from deploy"

workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
