version: 2.1

orbs:
  node: circleci/node@3.0.1

jobs:
  publish:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Publish to NPM
          command: |
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            npm publish

workflows:
  build-and-deploy:
    jobs:
      - node/test

      - publish:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
