version: 2.1

jobs:
  test:
    docker: 
      - image: circleci/node 
    steps:
      - checkout 
      - run: echo "hello test" 

  deploy:
    docker: 
      - image: circleci/node 
    steps:
      - checkout 
      - run: echo "hello deploy" 
    

workflows:
  test-and-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
