version: 2

jobs:
  test:
    docker: 
      - image: circleci/node # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello test" # run the `echo` command

  deploy:
    docker: 
      - image: circleci/node # the primary container, where your job's commands are run
    steps:
      - checkout 
      - run: echo "hello deploy" # run the `echo` command
    

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
